### PR TITLE
Add reset sequence number function to Factory class

### PR DESCRIPTION
**Pull request by 8enSmith**
In the tests I am writing I import an instance of Factory. This instance of factory is used by multiple tests. I don't want the sequence number to be incremented for subsequent tests, I want to reset the sequence number. I could instantiate a new instance of Factory in each test, but this would lead to needless duplication of code.

To address this problem I've written a function in the Factory class which resets the sequence number back to its starting value.

Let me know whether this is a sensible suggestion!

### CODE REVIEW

**Comment by willryan** [comment]
@8enSmith  can you make the same changes to `async.ts` / `async.spec.ts`?

Side note I'm going to remove lib/*.js from the repo momentarily so you won't have to worry about the merge conflict there.

**Comment by 8enSmith** [comment]
@willryan yes, no problem. I'll make the same changes to async.ts in the next couple of days.

**Comment by 8enSmith** [comment]
Hi @willryan , whilst adding the reset sequence number code to async.ts I found an issue with the existing async code with regards to the sequence numbers. Basically the existing async code does not appear to be increment the sequence number variable when run.

I've add a test to async.test.ts called "seq num works as expected" to demonstrate the problem. I'd expect the async code to increment the seq num by one for each outputted value, but the seqNum is not getting incremented (when I inspected the value I could see that seq num was zero for all generated objects).

Not sure what the best approach to fixing this existing issue is. Thoughts?

**Comment by willryan** [comment]
@8enSmith I think I've got a fix for the seqNum issues.

Two things:
- move `this.seqNum++;` immediately after the *local* seqNum is assigned. This guarantees that the seqNum is ready for subsequent calls even as nested data of this `build()`. This change can/should be made for both async.ts and sync.ts.
- change async's buildList function to await each item in turn:
```
public async buildList(count: number, item?: RecPartial<T>): Promise<T[]> {
    const ts: T[] = Array(count); // allocate to correct size
    // don't run in parallel, so that seq num works predictably
    for (let i = 0; i < count; i++) {
      ts[i] = await this.build(item);
    }
    return ts;
  }
```
This ensures predictable ordering of building and thus predictable ordering of sequence numbers.

Can you add these changes to your PR and then I'll merge it.  Also there are some merge conflicts to resolve.  You can ignore the lib/ ones, and I think the spec ones are probably just tests added in both places.

Thanks!

**Comment by 8enSmith** [comment]
Hi @willryan I have made the changes you have suggested. I've also dealt with the merge conflicts, the spec conflict was due to the new test from a different PR, and I've ignored the lib ones.

The tests all work, and the sequence number behaviour is now working as expected. Hopefully this PR should now be "good to go".

**Comment by 8enSmith** [comment]
Ok, so I had a few other changes that needed doing! This time I'm pretty sure my PR is done.

**Comment by 8enSmith** [comment]
@willryan you had a chance to look at this yet? Done what you suggested, should be good to go.

**Comment by willryan** [comment]
@8enSmith merged; I will create a new version and push to npm.

**Pull request merged**
